---
- name: mirror the manifests of the required operators from the new, custom index image on myregistry
  shell: sudo /usr/local/bin/oc adm catalog mirror myregistry:5000/myindeximages/my-{{index_image}}-index:v1 myregistry:5000 -a /run/containers/0/auth.json --manifests-only --insecure


- name: Get registry url for mirrored images
  shell: "tail -n 1 my-{{index_image}}-index-manifests/mapping.txt | awk -F'/' '{printf $1}'"
  register: url

- name: Get images registry for mirrored images
  shell: "tail -n 1 my-{{index_image}}-index-manifests/mapping.txt | awk -F'/' '{print $1}' | awk -F'.' '{printf $NF}'"
  register: url_prefix

- name: "Generate my_mapping.txt file."
  shell: "cat my-{{index_image}}-index-manifests/mapping.txt | awk -F'=' '{print $1}' | awk -F'{{url_prefix.stdout}}' '{print $2}' >> my_mapping.txt"
