---
- name: Generate htpasswd file to authenticate later to the registry
  command: htpasswd -bBc /tmp/myregistry/auth/htpasswd {{user}} {{password}}
  
- name: generate auth data for pull-secret.json file
  shell: echo -n "{{user}}:{{password}}" | base64 -w0
  register: output
- name: "Creating a pull-secret.json file with content for all registries"
  copy:
   dest: "/tmp/pull-secret.json"
   content: |
    {
      "auths": {
        "myregistry:5000": {
           "auth": '{{output.stdout}}',
           "username": "{{user}}",
           "password": "{{password}}"
         },
         "https://quay.io": {
           "auth": 'dGFtYmVyK3F1YXlfcHVsbF9yb2JvdDpOVzRBTTNBS1A3OEMzSTdHNVJQWklZUUhNVlZJOU5EWFdUUkNVVUxYRlJCS1BXVVJQRUZPNkZCNU5HMEg0T0FU',
           "email": ""
         },
         "https://registry.redhat.io": {
           "auth": 'MTI4NTA5MDR8cHVsbC1yb2JvdDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdNV0prTlRCbU1XTTBNVEEwTnpBNFlUaGlZMlF6WXprMllqWmhNak0yT1NKOS5nMHVuMk1xazhxUDBERWVzUEdfVTNvdzBzVGJtOEx4VFlmbUtINkt1TTBmYUFNX0hWWVNwdVMwTGswSjlPM2xqSlNEdHE4NnJScnlMZUR3elMwUEJsLUpPM2lwc05uOGxoNDFGd3lXUkRoc2luNmFTZ2NZc3gwVkFrQkV4T05meFpsNExJbkYzdF96cXRCWUdmVUpDMHRYaFdYd3ZabGZPNUU2bVY5V0tvX0VwV1QyeldReWRSS1hISllzV1A0Q1lnT3dseTF5VEZ3WHRKQ3lNUDNwTGRmcGNLRzRubXVRTlJjNmtIeE94NURiX3REUjh4S0hxT3ZrZnU4YUstQVh6RW1zZ0R6M2VISFJGd0dUVFYxSUtPd0d3aWYwMUpCM0kzakpTYThBVlBqT1MzM0cxdU81ZVVVWnFRdGdjX1RTQ05pVXhMdmNPV0tLVUZMaVdmVHZJdEZhY1g2UzluSV94X2FMZTBnSVdmVkpMUFJHZGVuY2pfX3Q3VXlnVDFKTGRzSWJXQ21yOVY4T2x4amROdkRKeGRlLU0zNlVhS3k4Q25udnpnNWx0cXozMnI0bGZ4X3NWOF9WOWg1ZVZza0xlLVRKS3ZWTlNkd0IyYUpkR29yaDhUTjRGY3RleW9FYk5YbEVzaTRkbXYwWG1rWktQRlpvOEVabHRUdzBMRXB1U3NUNG4yTXlTQVlObDRXXzRlWE9hV190cUQ1XzNmWF9LendoeV9SSFhERjNia3FJUExBRUw0SzJ0TkVKSnpIYVZuY2NSYzY5X2NoNzdoVjctZk5FbHBFaEtSTDNUb28wNWh1T0VGMnlFRlRFTDVQNDQ4SmdxeUVaMjNzTHNuVEFUd1VSUGlYM3pEWTRqMElpMktCeXV0YmN4SENOeEx1VVZWUUMtRDZzU0VlOA==',
           "username": '12850904|pull-robot',
           "password": 'eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiIwMWJkNTBmMWM0MTA0NzA4YThiY2QzYzk2YjZhMjM2OSJ9.g0un2Mqk8qP0DEesPG_U3ow0sTbm8LxTYfmKH6KuM0faAM_HVYSpuS0Lk0J9O3ljJSDtq86rRryLeDwzS0PBl-JO3ipsNn8lh41FwyWRDhsin6aSgcYsx0VAkBExONfxZl4LInF3t_zqtBYGfUJC0tXhWXwvZlfO5E6mV9WKo_EpWT2zWQydRKXHJYsWP4CYgOwly1yTFwXtJCyMP3pLdfpcKG4nmuQNRc6kHxOx5Db_tDR8xKHqOvkfu8aK-AXzEmsgDz3eHHRFwGTTV1IKOwGwif01JB3I3jJSa8AVPjOS33G1uO5eUUZqQtgc_TSCNiUxLvcOWKKUFLiWfTvItFacX6S9nI_x_aLe0gIWfVJLPRGdencj__t7UygT1JLdsIbWCmr9V8OlxjdNvDJxde-M36UaKy8Cnnvzg5ltqz32r4lfx_sV8_V9h5eVskLe-TJKvVNSdwB2aJdGorh8TN4FcteyoEbNXlEsi4dmv0XmkZKPFZo8EZltTw0LEpuSsT4n2MySAYNl4W_4eXOaW_tqD5_3fX_Kzwhy_RHXDF3bkqIPLAEL4K2tNEJJzHaVnccRc69_ch77hV7-fNElpEhKRL3Too05huOEF2yEFTEL5P448JgqyEZ23sLsnTATwURPiX3zDY4j0Ii2KByutbcxHCNxLuUVVQC-D6sSEe8'
         },
         "https://registry.connect.redhat.com": {
          "auth": 'MTI4NTA5MDR8cHVsbC1yb2JvdDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdNV0prTlRCbU1XTTBNVEEwTnpBNFlUaGlZMlF6WXprMllqWmhNak0yT1NKOS5nMHVuMk1xazhxUDBERWVzUEdfVTNvdzBzVGJtOEx4VFlmbUtINkt1TTBmYUFNX0hWWVNwdVMwTGswSjlPM2xqSlNEdHE4NnJScnlMZUR3elMwUEJsLUpPM2lwc05uOGxoNDFGd3lXUkRoc2luNmFTZ2NZc3gwVkFrQkV4T05meFpsNExJbkYzdF96cXRCWUdmVUpDMHRYaFdYd3ZabGZPNUU2bVY5V0tvX0VwV1QyeldReWRSS1hISllzV1A0Q1lnT3dseTF5VEZ3WHRKQ3lNUDNwTGRmcGNLRzRubXVRTlJjNmtIeE94NURiX3REUjh4S0hxT3ZrZnU4YUstQVh6RW1zZ0R6M2VISFJGd0dUVFYxSUtPd0d3aWYwMUpCM0kzakpTYThBVlBqT1MzM0cxdU81ZVVVWnFRdGdjX1RTQ05pVXhMdmNPV0tLVUZMaVdmVHZJdEZhY1g2UzluSV94X2FMZTBnSVdmVkpMUFJHZGVuY2pfX3Q3VXlnVDFKTGRzSWJXQ21yOVY4T2x4amROdkRKeGRlLU0zNlVhS3k4Q25udnpnNWx0cXozMnI0bGZ4X3NWOF9WOWg1ZVZza0xlLVRKS3ZWTlNkd0IyYUpkR29yaDhUTjRGY3RleW9FYk5YbEVzaTRkbXYwWG1rWktQRlpvOEVabHRUdzBMRXB1U3NUNG4yTXlTQVlObDRXXzRlWE9hV190cUQ1XzNmWF9LendoeV9SSFhERjNia3FJUExBRUw0SzJ0TkVKSnpIYVZuY2NSYzY5X2NoNzdoVjctZk5FbHBFaEtSTDNUb28wNWh1T0VGMnlFRlRFTDVQNDQ4SmdxeUVaMjNzTHNuVEFUd1VSUGlYM3pEWTRqMElpMktCeXV0YmN4SENOeEx1VVZWUUMtRDZzU0VlOA==',
          "username": '12850904|pull-robot',
          "password": 'eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiIwMWJkNTBmMWM0MTA0NzA4YThiY2QzYzk2YjZhMjM2OSJ9.g0un2Mqk8qP0DEesPG_U3ow0sTbm8LxTYfmKH6KuM0faAM_HVYSpuS0Lk0J9O3ljJSDtq86rRryLeDwzS0PBl-JO3ipsNn8lh41FwyWRDhsin6aSgcYsx0VAkBExONfxZl4LInF3t_zqtBYGfUJC0tXhWXwvZlfO5E6mV9WKo_EpWT2zWQydRKXHJYsWP4CYgOwly1yTFwXtJCyMP3pLdfpcKG4nmuQNRc6kHxOx5Db_tDR8xKHqOvkfu8aK-AXzEmsgDz3eHHRFwGTTV1IKOwGwif01JB3I3jJSa8AVPjOS33G1uO5eUUZqQtgc_TSCNiUxLvcOWKKUFLiWfTvItFacX6S9nI_x_aLe0gIWfVJLPRGdencj__t7UygT1JLdsIbWCmr9V8OlxjdNvDJxde-M36UaKy8Cnnvzg5ltqz32r4lfx_sV8_V9h5eVskLe-TJKvVNSdwB2aJdGorh8TN4FcteyoEbNXlEsi4dmv0XmkZKPFZo8EZltTw0LEpuSsT4n2MySAYNl4W_4eXOaW_tqD5_3fX_Kzwhy_RHXDF3bkqIPLAEL4K2tNEJJzHaVnccRc69_ch77hV7-fNElpEhKRL3Too05huOEF2yEFTEL5P448JgqyEZ23sLsnTATwURPiX3zDY4j0Ii2KByutbcxHCNxLuUVVQC-D6sSEe8'
         }
       }
    }
  
- name: "mkdir for root auth.json (based on an official solution https://access.redhat.com/solutions/5312991)"
  file:
    path: /run/containers/0
    state: directory
  
- name: Copying the new pull-secret.json file to /run/user/0/containers/auth.json file
  copy:
    src: /tmp/pull-secret.json
    dest: /run/containers/0/auth.json
